/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *image1;
  GtkWidget *hseparator1;
  GtkWidget *hbox2;
  GtkWidget *label3;
  GtkWidget *abrir;
  GtkWidget *image2;
  GtkWidget *gravar;
  GtkWidget *image3;
  GtkWidget *vseparator1;
  GtkWidget *full;
  GtkWidget *image4;
  GtkWidget *sair;
  GtkWidget *image5;
  GtkWidget *label2;
  GtkWidget * fs_abrir;
  GtkWidget * fs_gravar;

  GtkWidget * fs_erro = create_j_erro();
  

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("PL"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 430, 330);
  gtk_window_set_resizable(GTK_WINDOW (window1),TRUE);
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER_ALWAYS);

  fs_abrir = create_filechooserdialog1(window1);
  fs_gravar = create_filechooserdialog2(window1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport1), GTK_SHADOW_NONE);

  image1 = create_pixmap (window1, "eeng2.png");
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (viewport1), image1);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, TRUE, 2);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, FALSE, 1);
  gtk_widget_set_size_request (hbox2, -1, 29);

  label3 = gtk_label_new ("");
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, TRUE, FALSE, 0);

  abrir = gtk_button_new ();
  gtk_widget_show (abrir);
  gtk_box_pack_start (GTK_BOX (hbox2), abrir, FALSE, FALSE, 2);
  gtk_button_set_relief (GTK_BUTTON (abrir), GTK_RELIEF_NONE);

  image2 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (abrir), image2);

  gravar = gtk_button_new ();
  gtk_widget_show (gravar);
  gtk_widget_set_sensitive(gravar,FALSE);
  gtk_box_pack_start (GTK_BOX (hbox2), gravar, FALSE, FALSE, 2);
  gtk_button_set_relief (GTK_BUTTON (gravar), GTK_RELIEF_NONE);

  image3 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (gravar), image3);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox2), vseparator1, FALSE, TRUE, 2);
  gtk_widget_set_size_request (vseparator1, -1, 14);

  full = gtk_toggle_button_new ();
  gtk_widget_show (full);
  gtk_box_pack_start (GTK_BOX (hbox2), full, FALSE, FALSE, 2);
  gtk_button_set_relief (GTK_BUTTON (full), GTK_RELIEF_NONE);

  image4 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (full), image4);

  sair = gtk_button_new ();
  gtk_widget_show (sair);
  gtk_box_pack_start (GTK_BOX (hbox2), sair, FALSE, FALSE, 2);
  gtk_button_set_relief (GTK_BUTTON (sair), GTK_RELIEF_NONE);

  image5 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (sair), image5);

  label2 = gtk_label_new ("");
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, TRUE, FALSE, 0);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
                    
  g_signal_connect ((gpointer) abrir, "clicked",
                    G_CALLBACK (on_abrir_clicked),
                    (gpointer) window1);
                    
  g_signal_connect ((gpointer) gravar, "clicked",
                    G_CALLBACK (on_gravar_activate),
                    (gpointer) window1);
                    
  g_signal_connect ((gpointer) full, "toggled",
                    G_CALLBACK (on_full_toggled),
                    (gpointer) window1);
                    
  g_signal_connect ((gpointer) sair, "clicked",
                    G_CALLBACK (on_sair_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, abrir, "abrir");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, gravar, "gravar");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window1, full, "full");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, sair, "sair");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, fs_abrir, "fs_abrir");
  GLADE_HOOKUP_OBJECT (window1, fs_gravar, "fs_gravar");
  GLADE_HOOKUP_OBJECT (window1, fs_erro, "fs_erro");

  return window1;
}

GtkWidget*
create_filechooserdialog1 (GtkWidget * t)
{
  GtkWidget *filechooserdialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *button14;
  GtkWidget *button15;

  filechooserdialog1 = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (filechooserdialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (filechooserdialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  button14 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button14);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button14, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button14, GTK_CAN_DEFAULT);

  button15 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button15);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button15, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button15, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_a_cancelar_clicked),
                     t);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_a_abrir_clicked),
                    t);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, filechooserdialog1, "filechooserdialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button14, "button14");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button15, "button15");

  gtk_widget_grab_default (button15);
  return filechooserdialog1;
}

GtkWidget*
create_filechooserdialog2 (GtkWidget * t)
{
  GtkWidget *filechooserdialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *dialog_action_area2;
  GtkWidget *button16;
  GtkWidget *button17;

  filechooserdialog2 = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_SAVE, NULL);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog2), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (filechooserdialog2)->vbox;
  gtk_widget_show (dialog_vbox2);

  dialog_action_area2 = GTK_DIALOG (filechooserdialog2)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  button16 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button16);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog2), button16, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  button17 = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_show (button17);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog2), button17, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_g_cancelar_clicked),
                    (gpointer) t);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_g_gravar_clicked),
                    (gpointer) t);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog2, filechooserdialog2, "filechooserdialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (filechooserdialog2, button16, "button16");
  GLADE_HOOKUP_OBJECT (filechooserdialog2, button17, "button17");

  gtk_widget_grab_default (button17);
  return filechooserdialog2;
}

GtkWidget*
create_j_erro (void)
{
  GtkWidget *j_erro;
  GtkWidget *vbox2;
  GtkWidget *hbox10;
  GtkWidget *e_image;
  GtkWidget *e_label;
  GtkWidget *e_ok;
  GtkWidget *alignment6;
  GtkWidget *hbox9;
  GtkWidget *image14;
  GtkWidget *label10;

  j_erro = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (j_erro, 350, 160);
  gtk_window_set_title (GTK_WINDOW (j_erro), _("j_erro"));
  gtk_window_set_default_size (GTK_WINDOW (j_erro), 350, 160);
  gtk_window_set_position (GTK_WINDOW (j_erro), GTK_WIN_POS_CENTER_ALWAYS);
//  gtk_window_set_resizable (GTK_WINDOW (j_erro), FALSE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (j_erro), vbox2);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox10, TRUE, TRUE, 0);

  e_image = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (e_image);
  gtk_box_pack_start (GTK_BOX (hbox10), e_image, FALSE, TRUE, 0);
  gtk_widget_set_size_request (e_image, 60, -1);

  e_label = gtk_label_new ("");
  gtk_widget_show (e_label);
  gtk_box_pack_start (GTK_BOX (hbox10), e_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (e_label), GTK_JUSTIFY_CENTER);

  e_ok = gtk_button_new ();
  gtk_widget_show (e_ok);
  gtk_box_pack_start (GTK_BOX (vbox2), e_ok, FALSE, FALSE, 3);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (e_ok), alignment6);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox9);

  image14 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox9), image14, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox9), label10, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) e_ok, "clicked",
                    G_CALLBACK (on_e_ok_clicked),
                    (gpointer) j_erro);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (j_erro, j_erro, "j_erro");
  GLADE_HOOKUP_OBJECT (j_erro, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (j_erro, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (j_erro, e_image, "e_image");
  GLADE_HOOKUP_OBJECT (j_erro, e_label, "e_label");
  GLADE_HOOKUP_OBJECT (j_erro, e_ok, "e_ok");
  GLADE_HOOKUP_OBJECT (j_erro, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (j_erro, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (j_erro, image14, "image14");
  GLADE_HOOKUP_OBJECT (j_erro, label10, "label10");

  return j_erro;
}
