/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_filechooserdialog1 (GtkWidget * t);
GtkWidget* create_filechooserdialog2 (GtkWidget * t);
GtkWidget* create_j_erro ();
